---
- name: Generate locales
  command: locale-gen {{locale}}

- name: Update locale
  command: update-locale LANGUAGE={{language}} LANG={{locale}} LC_ALL={{locale}}
  
- name: Set system locale
  shell: . /etc/default/locale

- name: Install Required Packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - libpq-dev
    - openjdk-6-jdk
    - postgresql
    - python-psycopg2
    - solr-jetty
    
- name: Start DB Cluster
  command: /etc/init.d/postgresql start
    
- name: Create DB
  sudo_user: postgres
  postgresql_db: name={{ckan_db}} encoding="UTF-8" lc_collate={{locale}} lc_ctype={{locale}} template=template0
  
- name: Change pg_hba.conf
  copy: src=roles/postgresql-server/files/pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf force=yes
  
- name: Enable PostgreSQL remote connection
  copy: src=roles/postgresql-server/files/postgresql.conf dest=/etc/postgresql/9.1/main/postgresql.conf force=yes
  
- name: Get iptables rules
  shell: iptables -L
  register: iptablesrules
  always_run: yes
  sudo: true
 
- name: Add PostgreSQL iptable rule
  command: iptables -A INPUT -p tcp -s 0/0 --sport 1024:65535 -d 192.168.33.10 --dport 5432 -m state --state NEW,ESTABLISHED -j ACCEPT -m comment --comment "postgresql"
  command: iptables -A OUTPUT -p tcp -s 192.168.33.10 --sport 5432 -d 0/0 --dport 1024:65535 -m state --state ESTABLISHED -j ACCEPT -m comment --comment "postgresql"
  sudo: true
  when: iptablesrules.stdout.find("postgresql") == -1
 
- name: save iptables
  command: iptables-save
  sudo: true
 
- name: restart iptables
  service: name=ufw state=restarted
  sudo: true 
  
- name: Reload PostgreSQL
  service: name=postgresql state=reloaded

- name: Create ckan db user
  sudo_user: postgres
  postgresql_user: db={{ckan_db}} name={{ckan_user}} password={{pg_password}} priv=ALL

- name: Copy Jetty configuration to remote host
  copy: src=roles/postgresql-server/files/jetty dest=/etc/default/jetty force=yes

- name: Start Jetty Server
  service: name=jetty state=started

#- name: Backup Solr schema
#  command: mv /etc/solr/conf/schema.xml /etc/solr/conf/schema.xml.bak

- name: Replace Solr schema.xml with CKAN schema file
  copy: src=schema-2.0.xml dest=/etc/solr/conf/schema.xml force=yes
  
- name: Schema in usr/share
  copy: src=schema-2.0.xml dest=/usr/share/solr/conf/schema.xml force=yes

- name: Restart Jetty Server
  service: name=jetty state=restarted
  